/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin-panel/': RouteRecordInfo<'/admin-panel/', '/admin-panel', Record<never, never>, Record<never, never>>,
    '/admin-panel/Blogs': RouteRecordInfo<'/admin-panel/Blogs', '/admin-panel/Blogs', Record<never, never>, Record<never, never>>,
    '/admin-panel/Create': RouteRecordInfo<'/admin-panel/Create', '/admin-panel/Create', Record<never, never>, Record<never, never>>,
    '/admin-panel/Profile': RouteRecordInfo<'/admin-panel/Profile', '/admin-panel/Profile', Record<never, never>, Record<never, never>>,
    '/Index': RouteRecordInfo<'/Index', '/Index', Record<never, never>, Record<never, never>>,
  }
}
